logging.level:
  root: info

server : 
  port : 80

spring:
  main:
    log-startup-info: true
    lazy-initialization : false
  application :
    admin :
        enabled : true
  servlet : 
     multipart :
          enabled: true
          location: ${java.io.tmpdir}
          max-file-size : 400MB
          max-request-size : 100MB
          file-size-threshold: 1MB
  h2:
     console:
         enabled: true
         path: /h2 # default /h2-console
 
